name: Notify Projects
on:
  push:
    branches: [ main ] # 共通リポジトリのメインブランチ名

jobs:
  dispatch:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # 1つ失敗しても他を止めない
      matrix:
        # 同期先のプロジェクトリポジトリをすべてリストアップ
        repo: 
          - 'zaz4416/Hellow_World_for_Adobe_Illustrator'
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }} # repo権限を持つPAT
          repository: ${{ matrix.repo }}
          event-type: common_lib_updated
