name: Notify Projects
on:
  push:
    branches: [ main, master ] # mainでもmasterでも動くようにする
  workflow_dispatch: # ★これでブラウザから手動実行できるかテストできる

jobs:
  dispatch:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ['zaz4416/ImageViewer_for_Adobe_Illustrator', 'zaz4416/Hellow_World_for_Adobe_Illustrator']
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: common_lib_updated
          client-payload: '{"target_repo": "${{ matrix.repo }}"}'
